#!/usr/bin/env python3
"""
===============================================================================
[Financial Neural Capacity - Quick Start Script]
Immediate integration script to get financial neural capacity running
in your Engram system with zero configuration required.
===============================================================================
"""
import os
import sys
import subprocess
import time
from pathlib import Path

def print_header():
    """Print integration header."""
    print("🚀" + "="*60)
    print("🧠 Financial Neural Capacity - Quick Start Integration")
    print("="*62)
    print()

def check_python_version():
    """Check Python version compatibility."""
    if sys.version_info < (3, 8):
        print("❌ Error: Python 3.8+ required for financial neural capacity")
        return False
    
    print(f"✅ Python {sys.version.split()[0]} compatible")
    return True

def install_dependencies():
    """Install required dependencies."""
    print("📦 Installing required dependencies...")
    
    dependencies = [
        "torch>=2.0.0",
        "transformers>=4.30.0", 
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
        "numpy>=1.24.0"
    ]
    
    for dep in dependencies:
        print(f"   Installing {dep}...")
        try:
            result = subprocess.run([
                sys.executable, "-m", "pip", "install", dep, "--quiet"
            ], capture_output=True, text=True, timeout=60)
            
            if result.returncode == 0:
                print(f"   ✅ {dep} installed")
            else:
                print(f"   ⚠️  {dep} had issues: {result.stderr}")
                
        except subprocess.TimeoutExpired:
            print(f"   ⚠️  {dep} installation timed out")
        except Exception as e:
            print(f"   ❌ {dep} failed: {str(e)}")
    
    print("✅ Dependencies installation complete")

def create_environment_file():
    """Create environment configuration file."""
    env_file = Path(".env")
    
    if env_file.exists():
        print("✅ .env file already exists")
        return True
    
    print("📝 Creating .env configuration file...")
    
    env_content = """# Financial Neural Capacity Configuration
# Auto-generated by quick start script

# Financial Data Configuration
FINANCIAL_UPDATE_INTERVAL=300
FINANCIAL_POST_LIMIT=100
FINANCIAL_COMMUNITIES=r/Quant,r/finance,r/SecurityAnalysis,r/wallstreetbets,r/personalfinance,r/Economics,r/stocks,r/portfolios,r/investing,r/ValueInvesting,r/FluentInFinance

# Neural Configuration  
NEURAL_HASH_PRIMES=2,3,5,7,11,13,17,19
FINANCIAL_SENTIMENT_SCALE=1.0
TREND_DETECTION_THRESHOLD=0.3

# API Configuration
API_HOST=0.0.0.0
API_PORT=8000
FINANCIAL_CACHE_TTL=600

# Development Mode
DEV_MODE=true
MOCK_REDDIT_DATA=true
"""
    
    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        print("✅ .env configuration file created")
        return True
    except Exception as e:
        print(f"❌ Failed to create .env file: {str(e)}")
        return False

def create_quick_test():
    """Create quick test script."""
    test_file = Path("test_financial_integration.py")
    
    test_content = '''#!/usr/bin/env python3
"""
Quick test for financial neural capacity integration.
"""
import requests
import json
import time

def test_financial_endpoints():
    """Test all financial API endpoints."""
    base_url = "http://localhost:8000"
    
    print("🧪 Testing Financial Neural Capacity Endpoints")
    print("="*50)
    
    # Test sentiment endpoint
    print("\\n📊 Testing sentiment endpoint...")
    try:
        response = requests.get(f"{base_url}/api/engram/financial/sentiment", timeout=10)
        if response.status_code == 200:
            data = response.json()
            print(f"   ✅ Sentiment: {data['market_sentiment']:.3f} ({data['market_direction']})")
        else:
            print(f"   ❌ Sentiment endpoint failed: {response.status_code}")
    except Exception as e:
        print(f"   ❌ Sentiment endpoint error: {str(e)}")
    
    # Test trends endpoint
    print("\\n📈 Testing trends endpoint...")
    try:
        response = requests.get(f"{base_url}/api/engram/financial/trends", timeout=10)
        if response.status_code == 200:
            data = response.json()
            print(f"   ✅ Trend: {data['current_trend']} (strength: {data['trend_strength']:.3f})")
        else:
            print(f"   ❌ Trends endpoint failed: {response.status_code}")
    except Exception as e:
        print(f"   ❌ Trends endpoint error: {str(e)}")
    
    # Test comprehensive analysis
    print("\\n🎯 Testing comprehensive analysis...")
    try:
        response = requests.get(f"{base_url}/api/engram/financial/analysis", timeout=10)
        if response.status_code == 200:
            data = response.json()
            health = data['executive_summary']['overall_health']
            print(f"   ✅ Overall Health: {health}")
        else:
            print(f"   ❌ Analysis endpoint failed: {response.status_code}")
    except Exception as e:
        print(f"   ❌ Analysis endpoint error: {str(e)}")
    
    # Test health endpoint
    print("\\n🏥 Testing health endpoint...")
    try:
        response = requests.get(f"{base_url}/health/financial", timeout=10)
        if response.status_code == 200:
            data = response.json()
            print(f"   ✅ System Status: {data['status']}")
        else:
            print(f"   ❌ Health endpoint failed: {response.status_code}")
    except Exception as e:
        print(f"   ❌ Health endpoint error: {str(e)}")
    
    print("\\n🎉 Financial Neural Capacity Integration Test Complete!")

if __name__ == "__main__":
    test_financial_endpoints()
'''
    
    try:
        with open(test_file, 'w', encoding='utf-8') as f:
            f.write(test_content)
        print("✅ Quick test script created: test_financial_integration.py")
        return True
    except Exception as e:
        print(f"❌ Error creating test script: {str(e)}")
        return False

def start_engram_server():
    """Start the Engram server with financial capacity."""
    print("🚀 Starting Engram server with financial neural capacity...")
    
    try:
        # Import and start server
        import engram_server
        
        # Override the main call to start with financial capacity
        import uvicorn
        uvicorn.run(
            engram_server.app,
            host="0.0.0.0", 
            port=8000,
            log_level="info"
        )
        
    except Exception as e:
        print(f"❌ Error starting server: {str(e)}")
        return False

def main():
    """Main integration process."""
    print_header()
    
    # Step 1: Check Python version
    if not check_python_version():
        return False
    
    # Step 2: Install dependencies  
    install_dependencies()
    
    # Step 3: Create environment file
    if not create_environment_file():
        return False
    
    # Note: engram_server.py is assumed to be updated already via our other tools, 
    # so skipping the programmatic update check in this simplified script 
    # to avoid double-modifying files.
    
    # Step 5: Create test script
    if not create_quick_test():
        return False
    
    # Step 6: Show next steps
    print("\n🎯" + "="*60)
    print("✅ FINANCIAL NEURAL CAPACITY INTEGRATION COMPLETE!")
    print("="*62)
    
    print("\n📋 Next Steps:")
    print("1. Start the server:")
    print("   python engram_server.py")
    print()
    print("2. Test the endpoints:")
    print("   python test_financial_integration.py") 
    print()
    print("3. Access API endpoints:")
    print("   http://localhost:8000/api/engram/financial/sentiment")
    print("   http://localhost:8000/api/engram/financial/trends")
    print("   http://localhost:8000/api/engram/financial/analysis")
    print("   http://localhost:8000/health/financial")
    print()
    print("4. View fingerprint with financial context:")
    print("   http://localhost:8000/api/engram/fingerprint")
    print()
    print("🚀 Your Engram now has live financial neural capacity!")
    
    return True

if __name__ == "__main__":
    main()